# Generated by Django 3.2.7 on 2021-09-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciencia_y_Tecnología',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('area', models.CharField(max_length=100)),
                ('grado', models.CharField(max_length=50)),
                ('docente', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comunicación_y_lenguaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('area', models.CharField(max_length=100)),
                ('grado', models.CharField(max_length=50)),
                ('docente', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Convivencia_y_Sociedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('area', models.CharField(max_length=100)),
                ('grado', models.CharField(max_length=50)),
                ('docente', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Campos',
        ),
    ]
