# Generated by Django 3.2.7 on 2021-09-29 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0002_auto_20210929_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciencia_y_tecnología',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='comunicación_y_lenguaje',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='convivencia_y_sociedad',
            name='nombre',
        ),
    ]
