# Generated by Django 3.0.8 on 2021-10-04 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Asignaturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuantitativa', models.FloatField(default=0)),
                ('cualitativa', models.CharField(max_length=200)),
                ('estudiante', models.CharField(max_length=200)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asignaturas.materias')),
            ],
        ),
    ]
